export { Header } from './Header'
export { Footer } from './Footer'
export { PublicOnly } from './PublicOnly'
export { SkipLink } from './SkipLink'
export { ThemeSwitch, type ThemeSwitchProps } from './ThemeSwitch'
export { OpenIndexButton } from './IndexButton'
export { openIndex, openContents } from './events'
export type { ThemeLabels, NavSection, IndexEntry } from './types'
